import "./globals.css";
import React from "react";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

export const metadata = {
  title: "Graha Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
      <body style={{ paddingTop: "-20px", marginTop: "-20px" }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
